services:
  proxy:
    image: nginx:latest
    ports:
      - "443:8443"
    volumes:
      - ./nginx/proxy.conf:/etc/nginx/conf.d/default.conf
      - ./nginx/ssl:/etc/nginx/ssl:ro
    depends_on:
      - varnish
    networks:
      - magento-network
    restart: unless-stopped
  web:
    image: nginx:latest
    ports:
      - "8000:8000"
    volumes:
      - ./src:/var/www/html
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    working_dir: /var/www/html/
    restart: unless-stopped
    depends_on:
      - php
      - db
      - opensearch
    networks:
      - magento-network
  varnish:
    image: varnish:7.1
    ports:
      - "80:80"
      - "6082:6082"
    volumes:
      - ./varnish/default.vcl:/etc/varnish/default.vcl:ro
    depends_on:
      - web
    networks:
      - magento-network
    environment:
      - VARNISH_SIZE=1G
    deploy:
      resources:
        limits:
          memory: 1G
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "varnishadm", "ping"]
      interval: 30s
      timeout: 10s
      retries: 3
  php:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        user: magento
        uid: 1000
    volumes:
      - ./src:/var/www/html
      - ./php/custom.ini:/usr/local/etc/php/conf.d/custom.ini:ro
    depends_on:
      - db
      - redis
      - opensearch
      - rabbitmq
    networks:
      - magento-network
    deploy:
      resources:
        limits:
          memory: 2G
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "php", "-v"]
      interval: 30s
      timeout: 10s
      retries: 3
  db:
    image: mariadb:10.6
    command: --max_allowed_packet=128M --innodb-buffer-pool-size=1G --transaction-isolation=READ-COMMITTED --log-bin=binlog --binlog-format=ROW
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=magento
      - MYSQL_DATABASE=magento
      - MYSQL_USER=magento
      - MYSQL_PASSWORD=magento
    volumes:
      - dbdata:/var/lib/mysql
      - ./mysql/my.cnf:/etc/mysql/conf.d/my.cnf:ro
    networks:
      - magento-network
    deploy:
      resources:
        limits:
          memory: 2G
  opensearch:
    image: opensearchproject/opensearch:2.12.0
    ports:
      - "9200:9200"
      - "9600:9600"
    environment:
      - discovery.type=single-node
      - bootstrap.memory_lock=true
      - "OPENSEARCH_JAVA_OPTS=-Xms512m -Xmx512m"
      - "DISABLE_SECURITY_PLUGIN=true"
      - "OPENSEARCH_JAVA_OPTS=-Xms512m -Xmx512m -Dos.metrics.cgroup.cpu.path=/ -Dos.metrics.cgroup.memory.path=/"
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536
    volumes:
      - opensearchdata:/usr/share/opensearch/data
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
    networks:
      - magento-network
    deploy:
      resources:
        limits:
          memory: 1G
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9200/_cluster/health?pretty"]
      interval: 30s
      timeout: 10s
      retries: 3
    restart: unless-stopped
  redis:
    image: redis:7.2
    ports:
      - "6379:6379"
    volumes:
      - redisdata:/data
    networks:
      - magento-network
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 30s
      timeout: 10s
      retries: 3
    restart: unless-stopped
  redis-session:
    image: redis:7.2
    ports:
      - "6380:6380"
    volumes:
      - redissessiondata:/data
    networks:
      - magento-network
    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]
      interval: 30s
      timeout: 10s
      retries: 3
    restart: unless-stopped
  rabbitmq:
    image: rabbitmq:3.13-management
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      - RABBITMQ_DEFAULT_USER=magento
      - RABBITMQ_DEFAULT_PASS=magento
    volumes:
      - rabbitmqdata:/var/lib/rabbitmq
    networks:
      - magento-network
    deploy:
      resources:
        limits:
          memory: 1G
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "rabbitmqctl", "status"]
      interval: 30s
      timeout: 10s
      retries: 3
networks:
  magento-network:
    driver: bridge

volumes:
  dbdata:
  redisdata:
  redissessiondata:
  opensearchdata:
  rabbitmqdata:

